DROP TABLE IF EXISTS shows CASCADE;
DROP TABLE IF EXISTS episodes CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS user_episode_joins CASCADE;
DROP TABLE IF EXISTS user_show_joins CASCADE;
